config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :addresses
  resources :contacts
  resources :kinds
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind # contato pertence a um tipo
  has_one :address# contato possui um endereço
  has_many :phones, dependent: :destroy# contato possui muitos telefones

  accepts_nested_attributes_for :address #aceita atributos de endereço
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_options_for_select, only: [:new, :edit, :update, :create]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(20)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address # cria um endereço e vincula com o usuário que esta sendo criado.
    
  end

  # GET /contacts/1/edit
  def edit
    
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_options_for_select
      @kind_options_for_select = Kind.all      
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :kind_id, :rmk, 
        address_attributes: [:id, :street, :city, :state],
        phones_attributes: [:id, :phone, :_destroy])
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :kind_id %>
    <%= collection_select(:contact, :kind_id, @kind_options_for_select, :id, :description) %>
  </div>

  <%= form.fields_for :address do |address_fields| %>
    <div class="field">
      <%= address_fields.label :street %>
      <%= address_fields.text_field :street %>
    </div>
    <div class="field">
      <%= address_fields.label :city %>
      <%= address_fields.text_field :city %>
    </div>
    <div class="field">
      <%= address_fields.label :state %>
      <%= address_fields.select :state, options_for_select([["Rio Grande do Sul", "RS"],["Santa Catarina", "SC"]], @contact.address.state) %>
    </div>
  <% end %>
  <div id="phones">
    <%= form.fields_for :phones do |phones_fields| %>
      <%= render partial: "phone_fields", locals: { f: phones_fields } %>
    <% end %>
    <div class="field">
      <%= form.label :phones, ">" %><br>
      <%= link_to_add_association('[Adicionar Telefone]', form, :phones) %>
    </div>
  </div>

  <div class="field">
    <%= form.label :rmk %>
    <%= form.text_area :rmk %>
  </div>

  <div class="actions">
    <%= form.submit "salvar", class: "button" %>
  </div>
<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "phone-field" %>
    <%= link_to_remove_association 'remover', f %>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="basic-grey">
    <h1>Editing Contact</h1>
        <%= render 'form', contact: @contact %>

        <%= link_to 'Show', @contact %> |
        <%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/index.html.erb
<div class="basic-grey">
  <p id="notice"><%= notice %></p>

  <h1><%= @contacts.model_name.human(count: @contacts.count) %></h1>
  
  <%= link_to t('buttons.newContact'), new_contact_path %>
  <table>
    <thead>
      <tr>
        <th><%= @contacts.human_attribute_name("name") %></th>
        <th><%= @contacts.human_attribute_name("kind") %></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.kind.description %></td>
          <td><%= link_to t('buttons.show'), contact %></td>
          <td><%= link_to t('buttons.edit'), edit_contact_path(contact) %></td>
          <td><%= link_to t('buttons.destroy'), contact, method: :delete, data: { confirm: t('messages.confirm') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= paginate @contacts %>
</div>

app/views/contacts/new.html.erb
<div class="basic-grey">
    <h1>New Contact</h1>

    <%= render 'form', contact: @contact %>

    <%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/show.html.erb
<div class="basic-grey">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @contact.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @contact.email %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= @contact.kind.description %>
  </p>

  <p>
    <strong>Rmk:</strong>
    <%= @contact.rmk %>
  </p>

  <%= link_to 'Edit', edit_contact_path(@contact) %> |
  <%= link_to 'Back', contacts_path %>
</div>